---
title: "PS270 Final Project"
author: "Landon Johnson"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to lobbying and how much certain fields/companies spend in lobbying. I believe it would be fascinating to see who/what companies have political influence. By analyzing this data, we will also be able to see what politicians support what companies/industries.




## Project Paragraph

My research question is how does the amount of money companies spend on lobbying affect the voting behavior of politicians on legislative decisions that impact those industries? My hypothesis is the more money a company or industry spends on lobbying, the more likely politicians are to support legislation that favors the industry’s interests. This hypothesis is rooted in the theory of political influence, where financial contributions by lobbying act as a means for industries to gain access and influence over politicians that make decisions. The independent variable is the amount of money spent on lobbying by companies, which can be measured in dollars. I can find data that tells me lobbying expenditures by industry and company over time. The dependent variable is the voting behavior of politicians, specifically how often they vote in favor of legislation that aligns with the interests of the lobbying industry/company. I can find data that measures the percentage of supportive votes based on data that is publicly available legislative records. If the data shows that as lobbying expenditures increase, the likelihood of favorable voting behavior by politicians also increases, this would support my hypothesis. Counter to that, if there is no systematic relationship or if increased lobbying leads to fewer favorable votes, this would disprove my hypothesis.
